### ISSUE TITLE
Make result downloadable

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [softwareengineerprogrammer/geothermal-ui#3]

**Comment by malcolm-dsider** [comment]
It would be more useful if clicking on that link next to the “Result” header allowed the user to download the result in some usable format. I think they would especially like to get the table of results as tables instead of graphics.

**Comment by softwareengineerprogrammer** [comment]
Resolved by https://github.com/softwareengineerprogrammer/geothermal-ui/commit/8ba972641fbd74d020328f652875bbbc618ef52f
